### ISSUE TITLE
telliot errors out when it fails to fetch fee info from eth gas station

### ISSUE THREAD

**Issue by Spuddyminer** [tellor-io/telliot-feed-examples#116]
Problem: Telliot process fails / errors out after running continuously for hours / days.
Expected Behavior: It keeps running forever until it runs out of gas.

Traceback attached. Hope this is good!

[traceback.txt](https://github.com/tellor-io/telliot-feed-examples/files/7989650/traceback.txt)

**Comment by oraclown** [comment]
Hey @akremstudy , @Spuddyminer is still getting errors from ethgasstation not returning a response. I looked at the code again (I should've caught this before we merged, I'm sorry) and there are some things that need to be fixed in (at least) `interval.py`:
- [ ] line 108 needs to return `Optional[int]` bc of your changes to `ethgasstation()` in `telliot-core`
- [ ] line 121 change the log to be a more sever type than info, also the msg should say unable to retrieve gas price or something, as the retying happens in the `ethgasstation()` function
- [ ] line 122 should return `False` and an error status
- [ ] line 137 should return if not staked or status is not okay probs
- [ ] also write enough tests to confirm that your changes have covered the gas price errors (you can create a mock for ethgasstation() so it doesn't return a gas price)

I suggest searching in the entire codebase (vscode and most major IDEs have an easy search bar for this) for uses of `ethgasstation` to make sure that all potential failed gas price fetches are covered

**Comment by akremstudy** [comment]
whats the error he's getting?

**Comment by oraclown** [comment]
> whats the error he's getting?

```
)\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 447, in report\n    _, _ = await self.report_once()\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 309, in report_once\n    staked, status = await self.ensure_staked()\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 119, in ensure_staked\n    gas_price_gwei = await self.fetch_gas_price()\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 110, in fetch_gas_price\n    return await ethgasstation(speed)  # type: ignore\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_core/gas/legacy_gas.py", line 23, in ethgasstation\n    prices = json.loads(rsp.content)\n', '  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n', '  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n', '  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode\n    raise JSONDecodeError("Expecting value", s, err.value) from None\n']
Traceback (most recent call last):
  File "/home/ubuntu/tenv/bin/telliot-examples", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feed_examples/cli.py", line 408, in report
    _, _ = await reporter.report()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 447, in report
    _, _ = await self.report_once()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 309, in report_once
    staked, status = await self.ensure_staked()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 119, in ensure_staked
    gas_price_gwei = await self.fetch_gas_price()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 110, in fetch_gas_price
    return await ethgasstation(speed)  # type: ignore
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_core/gas/legacy_gas.py", line 23, in ethgasstation
    prices = json.loads(rsp.content)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
